/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef base_CONSTANTS_H
#define base_CONSTANTS_H

#include "base_types.h"

namespace Base {

class baseConstants {
 public:
  baseConstants();

};

extern const baseConstants g_base_constants;

} // namespace

#endif
