/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "base_constants.h"

namespace Base {

const baseConstants g_base_constants;

baseConstants::baseConstants() {
}

} // namespace

