/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef base_TYPES_H
#define base_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/stdcxx.h>


namespace Base {

enum EngineFlags {
  PURGED = 1,
  DIRTY = 2,
  SUPER = 4,
  AFFECTED = 8,
  BUSY = 16
};

extern const std::map<int, const char*> _EngineFlags_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const EngineFlags val);

} // namespace

#endif
