/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "errorcodes_constants.h"

namespace ErrorCodes {

const errorcodesConstants g_errorcodes_constants;

errorcodesConstants::errorcodesConstants() {
}

} // namespace

