/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef errorcodes_CONSTANTS_H
#define errorcodes_CONSTANTS_H

#include "errorcodes_types.h"

namespace ErrorCodes {

class errorcodesConstants {
 public:
  errorcodesConstants();

};

extern const errorcodesConstants g_errorcodes_constants;

} // namespace

#endif
