/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef errorcodes_TYPES_H
#define errorcodes_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/stdcxx.h>


namespace ErrorCodes {

enum Code {
  None = 0,
  InvalidOffset = 1,
  InvalidInput = 2,
  InvalidPermissions = 3,
  NullNotAllowed = 4,
  OutOfRange = 5,
  LengthExceeded = 6,
  Unrecognized = 7,
  Other = 8,
  TOP = 9
};

extern const std::map<int, const char*> _Code_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const Code val);

} // namespace

#endif
