/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef genus_CONSTANTS_H
#define genus_CONSTANTS_H

#include "genus_types.h"

namespace Genus {

class genusConstants {
 public:
  genusConstants();

};

extern const genusConstants g_genus_constants;

} // namespace

#endif
