/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef genus_TYPES_H
#define genus_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/stdcxx.h>


namespace Genus {

enum Genus {
  UNDEFINED = 0,
  INT = 1,
  TYPE = 2,
  FLAGS = 3,
  STRING = 4,
  SSTRING = 5,
  LEXISTRING = 6,
  CONSTRAINT = 7,
  EDITABLE = 8,
  ELEMENT = 9,
  THING = 10,
  LOCATION = 11,
  SKILLSTORE = 12,
  VEGETABLE = 13,
  CREATURE = 14,
  WORLD = 15,
  AFFECT = 16,
  EVENT = 17,
  CONCENTRATION = 18,
  PROPERTY = 19,
  ACTION = 20,
  EXIT = 21,
  MIND = 22,
  TOP = 23
};

extern const std::map<int, const char*> _Genus_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const Genus val);

} // namespace

#endif
