/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef materials_CONSTANTS_H
#define materials_CONSTANTS_H

#include "materials_types.h"

namespace Materials {

class materialsConstants {
 public:
  materialsConstants();

};

extern const materialsConstants g_materials_constants;

} // namespace

#endif
