/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "materials_constants.h"

namespace Materials {

const materialsConstants g_materials_constants;

materialsConstants::materialsConstants() {
}

} // namespace

