/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef permissions_CONSTANTS_H
#define permissions_CONSTANTS_H

#include "permissions_types.h"



class permissionsConstants {
 public:
  permissionsConstants();

};

extern const permissionsConstants g_permissions_constants;



#endif
