/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "permissions_constants.h"



const permissionsConstants g_permissions_constants;

permissionsConstants::permissionsConstants() {
}



