/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef pronouns_CONSTANTS_H
#define pronouns_CONSTANTS_H

#include "pronouns_types.h"

namespace Pronouns {

class pronounsConstants {
 public:
  pronounsConstants();

};

extern const pronounsConstants g_pronouns_constants;

} // namespace

#endif
