/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef pronouns_TYPES_H
#define pronouns_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/stdcxx.h>


namespace Pronouns {

enum Pronouns {
  UNDEFINED = 0,
  NEUTER = 1,
  MALE = 2,
  FEMALE = 3,
  PLURAL = 4,
  TOP = 5
};

extern const std::map<int, const char*> _Pronouns_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const Pronouns val);

} // namespace

#endif
