/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "pronouns_constants.h"

namespace Pronouns {

const pronounsConstants g_pronouns_constants;

pronounsConstants::pronounsConstants() {
}

} // namespace

