/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "propertytypes_constants.h"

namespace PropertyTypes {

const propertytypesConstants g_propertytypes_constants;

propertytypesConstants::propertytypesConstants() {
}

} // namespace

