/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef propertytypes_CONSTANTS_H
#define propertytypes_CONSTANTS_H

#include "propertytypes_types.h"

namespace PropertyTypes {

class propertytypesConstants {
 public:
  propertytypesConstants();

};

extern const propertytypesConstants g_propertytypes_constants;

} // namespace

#endif
