/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef propertytypes_TYPES_H
#define propertytypes_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/stdcxx.h>


namespace PropertyTypes {

enum Types {
  Exit = 0,
  Ingestable = 1,
  Poison = 2,
  Light = 3,
  Weapon = 4,
  FireWeapon = 5,
  Missile = 6,
  Armor = 7,
  Container = 8,
  Mountable = 9,
  Decay = 10,
  Money = 11,
  Stats = 12,
  TOP = 13
};

extern const std::map<int, const char*> _Types_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const Types val);

} // namespace

#endif
