/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "proximities_constants.h"

namespace Proximities {

const proximitiesConstants g_proximities_constants;

proximitiesConstants::proximitiesConstants() {
}

} // namespace

