/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef proximities_TYPES_H
#define proximities_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/stdcxx.h>


namespace Proximities {

enum Proximities {
  INSIDE = 0,
  PEOPLE = 1,
  EQUIPPED = 2,
  LOCATION = 3,
  PROPERTYOF = 4,
  SOUGHT = 5,
  REMEMBERED = 6,
  TARGETED = 7,
  AFFECTING = 8,
  CONCENTRATING = 9,
  FOLLOWING = 10,
  STALKING = 11,
  MEMBEROF = 12,
  LISTENER = 13,
  TOP = 14
};

extern const std::map<int, const char*> _Proximities_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const Proximities val);

} // namespace

#endif
