/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef proximities_CONSTANTS_H
#define proximities_CONSTANTS_H

#include "proximities_types.h"

namespace Proximities {

class proximitiesConstants {
 public:
  proximitiesConstants();

};

extern const proximitiesConstants g_proximities_constants;

} // namespace

#endif
