/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "signals_constants.h"

namespace Signals {

const signalsConstants g_signals_constants;

signalsConstants::signalsConstants() {
}

} // namespace

