/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "skills_constants.h"

namespace Skills {

const skillsConstants g_skills_constants;

skillsConstants::skillsConstants() {
}

} // namespace

