/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef skills_CONSTANTS_H
#define skills_CONSTANTS_H

#include "skills_types.h"

namespace Skills {

class skillsConstants {
 public:
  skillsConstants();

};

extern const skillsConstants g_skills_constants;

} // namespace

#endif
