/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "things_constants.h"

namespace Things {

const thingsConstants g_things_constants;

thingsConstants::thingsConstants() {
}

} // namespace

