/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef things_CONSTANTS_H
#define things_CONSTANTS_H

#include "things_types.h"

namespace Things {

class thingsConstants {
 public:
  thingsConstants();

};

extern const thingsConstants g_things_constants;

} // namespace

#endif
