/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "typedefs_constants.h"



const typedefsConstants g_typedefs_constants;

typedefsConstants::typedefsConstants() {
}



