/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef typedefs_TYPES_H
#define typedefs_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/stdcxx.h>




typedef std::vector<std::string>  StringTable;

typedef std::vector<std::string>  StringList;

typedef std::map<std::string, std::string>  StringMap;

typedef int8_t SInt8;

typedef int16_t SInt16;

typedef int32_t SInt32;

typedef int64_t SInt64;



#endif
