/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef typedefs_CONSTANTS_H
#define typedefs_CONSTANTS_H

#include "typedefs_types.h"



class typedefsConstants {
 public:
  typedefsConstants();

};

extern const typedefsConstants g_typedefs_constants;



#endif
